name: docker

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
          
      - name: Log in DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
      - name: Run Buildx
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t karlheinzkurt/cpp-micro-service:latest --push .
